{{- if .Values.application.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}-route
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    demo.redhat.com/application: "{{ .Values.app.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  {{- if .Values.application.route.host }}
  host: {{ .Values.application.route.host }}
  {{- else }}
  host: {{ .Values.app.name }}.{{ .Values.deployer.domain }}
  {{- end }}
  path: {{ .Values.application.route.path }}
  to:
    kind: Service
    name: {{ .Values.app.name }}-service
  port:
    targetPort: {{ .Values.application.service.targetPort }}
  {{- if .Values.application.route.tls }}
  tls:
    termination: {{ .Values.application.route.tls.termination }}
  {{- end }}
{{- end }}