---
# ============================================================
# Showroom Lab Guide Deployment
# UPDATE showroom.content.repoUrl to point to your lab guide repository
# ============================================================
#
# Configuration (edit these values):
#   - SHOWROOM_GIT_REPO: Your Showroom content Git repository
#   - SHOWROOM_GIT_REF: Branch or tag to use
#   - SHOWROOM_ANTORA_PLAYBOOK: Antora playbook file name
#
# Default values:
#   SHOWROOM_GIT_REPO: https://github.com/rhpds/showroom_template_default.git
#   SHOWROOM_GIT_REF: main
#   SHOWROOM_ANTORA_PLAYBOOK: default-site.yml
# ============================================================

---
# Showroom ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showroom
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
# Showroom RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-showroom-sa
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: showroom
  namespace: showroom
---
# Showroom Nginx ConfigMap
kind: ConfigMap
metadata:
  name: showroom-proxy-config
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
apiVersion: v1
data:
  nginx.conf: |
    events {
    }
    error_log /dev/stdout info;
    http {
      include /etc/nginx/mime.types;
      proxy_cache off;
      expires -1;
      proxy_cache_path /dev/null keys_zone=mycache:10m;
      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }
      server {
        listen 8080;
        absolute_redirect off;
        location / {
          proxy_pass http://127.0.0.1:8000;
          expires off;
          proxy_cache off;
          proxy_pass_request_headers on;
          proxy_set_header Accept-Encoding "gzip";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /terminal/ {
          proxy_pass http://127.0.0.1:7681;
          rewrite ^/terminal/(.*)$ /$1 break;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
      }
    }
---
# Showroom User Data ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-userdata
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  user_data.yml: |
    demo_namespace: terminal-demo
    demo_app: hello-world
---
# Showroom PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: showroom-terminal-lab-user-home
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
# Showroom Service
apiVersion: v1
kind: Service
metadata:
  name: showroom
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: showroom
---
# Showroom Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom
    spec:
      serviceAccountName: showroom
      initContainers:
      - name: git-cloner
        image: "quay.io/rhpds/git-cloner:v1.1.2"
        env:
        - name: GIT_REPO_URL
          # UPDATE THIS to your Showroom content repository
          value: "https://github.com/rhpds/showroom_template_default.git"
        - name: GIT_REPO_REF
          value: "main"
        - name: CLONE_DIR
          value: "/showroom/repo"
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
      - name: antora-builder
        image: "quay.io/rhpds/antora:v1.0.1"
        env:
        - name: FILES_DIR
          value: "/showroom/repo"
        - name: OUTPUT_DIR
          value: "/showroom/www"
        - name: ANTORA_SITE_FILE
          value: "default-site.yml"
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/www
          name: showroom-files
          subPath: www
      containers:
      - name: nginx
        image: "quay.io/rhpds/nginx:1.25"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        ports:
        - name: web
          containerPort: 8080
      - name: content
        image: "quay.io/rhpds/showroom-content:v1.3.0"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: GIT_REPO_URL
          # UPDATE THIS to your Showroom content repository
          value: "https://github.com/rhpds/showroom_template_default.git"
        - name: GIT_REPO_REF
          value: "main"
        - name: ANTORA_PLAYBOOK
          value: "default-site.yml"
        - name: ZT_BUNDLE
          value: "https://github.com/rhpds/nookbag/releases/download/nookbag-v0.2.1/nookbag-v0.2.1.zip"
        - name: ZT_UI_ENABLED
          value: "true"
        volumeMounts:
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
        - mountPath: /showroom/www
          name: showroom-files
          subPath: www
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
      - name: terminal
        image: "quay.io/rhpds/openshift-showroom-terminal-ocp:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: terminal-lab-user-home
          mountPath: /home/lab-user
        ports:
        - containerPort: 7681
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: showroom-files
        emptyDir: {}
      - name: user-data
        configMap:
          name: showroom-userdata
      - name: nginx-config
        configMap:
          defaultMode: 420
          name: showroom-proxy-config
      - name: nginx-pid
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: terminal-lab-user-home
        persistentVolumeClaim:
          claimName: showroom-terminal-lab-user-home
---
# Showroom Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom
  namespace: showroom
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    haproxy.router.openshift.io/timeout: 1h
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  to:
    kind: Service
    name: showroom
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
