apiVersion: v2
name: my-field-content
description: A Helm chart for field-developed content
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@redhat.com