apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-prepull
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: image-prepull
  template:
    metadata:
      labels:
        app: image-prepull
    spec:
      initContainers:
      {{- range $index, $image := .Values.images }}
      - name: prepull-{{ $index }}
        image: {{ $image }}
        command: ["echo", "Image pulled: {{ $image }}"]
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
      {{- end }}
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 32Mi
      tolerations:
      - operator: Exists
      nodeSelector:
        node-role.kubernetes.io/worker: ""
